/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-11-03 05:50:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.remind.model.LikeDto;
import com.remind.model.ReplyDto;
import java.util.List;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/bottom.jsp", Long.valueOf(1478065606194L));
    _jspx_dependants.put("jar:file:/C:/work/sts-bundle/repository/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/common.jsp", Long.valueOf(1478143675392L));
    _jspx_dependants.put("/sidebar.jsp", Long.valueOf(1478143675322L));
    _jspx_dependants.put("jar:file:/C:/work/sts-bundle/repository/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1475646166263L));
    _jspx_dependants.put("/top.jsp", Long.valueOf(1478143675335L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.remind.model.LikeDto");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.remind.model.ReplyDto");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE PUBLIC>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>ReMind : [RE:AD MIND]</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".follower_post {\r\n");
      out.write("   position: relative;\r\n");
      out.write("   left: 5%;\r\n");
      out.write("   top: 50%;\r\n");
      out.write("}\r\n");
      out.write(".mywishlist_table {\r\n");
      out.write("   background-color: lightblue;\r\n");
      out.write("   border: black;\r\n");
      out.write("   border-style: solid;\r\n");
      out.write("   border-width: thin;\r\n");
      out.write("}\r\n");
      out.write(".upcomingevent_table {\r\n");
      out.write("   background-color: pink;\r\n");
      out.write("   border: black;\r\n");
      out.write("   border-style: solid;\r\n");
      out.write("   border-width: thin;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- 공통적으로 적용되는 BOOTSTRAP CDN자료들 시작 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"http://getbootstrap.com/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("\t<!-- 부가적인 테마 -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("\t<!-- 어코디언 적용을 위한 시험 -->\r\n");
      out.write("\t<script src=\"http://v4-alpha.getbootstrap.com/assets/js/vendor/tether.min.js\"></script>\r\n");
      out.write("\t<script src=\"http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"http://v4-alpha.getbootstrap.com/assets/js/docs.min.js\"></script>\r\n");
      out.write("\t<!-- Documentation extras -->\r\n");
      out.write("\t<link href=\"http://v4-alpha.getbootstrap.com/assets/css/docs.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<!-- 시험끝 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t.top_pd {\r\n");
      out.write("\t\tpadding-top: 2%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.bottom_pd {\r\n");
      out.write("\t\tpadding-bottom: 2%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.main_pd {\r\n");
      out.write("\t\tpadding-top: 15%;\r\n");
      out.write("\t\tpadding-bottom: 20%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.lbl_pd {\r\n");
      out.write("\t\tpadding-top: 3%\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.body_pd {\r\n");
      out.write("\t\tpadding-top: 70px;\r\n");
      out.write("\t\tpadding-bottom: 70px;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("<!-- 공통적으로 적용되는 BOOTSTRAP CDN자료들 시작 끝 -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<link rel=\"icon\" href=\"../../favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("<title>Fixed Top Navbar</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS common.jsp에 있음-->\r\n");
      out.write("<link href=\"http://getbootstrap.com/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\r\n");
      out.write("<link href=\"http://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Just for debugging purposes. Don't actually copy these 2 lines! -->\r\n");
      out.write("<!--[if lt IE 9]><script src=\"../../assets/js/ie8-responsive-file-warning.js\"></script><![endif]-->\r\n");
      out.write("<script src=\"http://getbootstrap.com/assets/js/ie-emulation-modes-warning.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"padding-top: 70px\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Fixed navbar -->\r\n");
      out.write("    <nav class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"index.jsp\"><span class=\"glyphicon glyphicon-gift\" aria-hidden=\"true\">RE:MIND</span></a></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav\">\r\n");
      out.write("            <li><a href=\"index.jsp\"><span class=\"glyphicon glyphicon-home\" aria-hidden=\"true\"></span></a></li>\r\n");
      out.write("            <li><a href=\"showWishList?w_mno=");
      out.print(session.getAttribute("mno"));
      out.write("\"><span class=\"glyphicon glyphicon-gift\" aria-hidden=\"true\"></span></a></li>\r\n");
      out.write("            <li><a href=\"myinfo.jsp\"><span class=\"glyphicon glyphicon-user\" aria-hidden=\"true\"></span></a></li>\r\n");
      out.write("            <li class=\"dropdown\">\r\n");
      out.write("              <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Dropdown <span class=\"caret\"></span></a>\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li><a href=\"#\">Action</a></li>\r\n");
      out.write("                <li><a href=\"#\">Another action</a></li>\r\n");
      out.write("                <li><a href=\"#\">Something else here</a></li>\r\n");
      out.write("                <li role=\"separator\" class=\"divider\"></li>\r\n");
      out.write("                <li class=\"dropdown-header\">Nav header</li>\r\n");
      out.write("                <li><a href=\"#\">Separated link</a></li>\r\n");
      out.write("                <li><a href=\"#\">One more separated link</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("            <li><a href=\"../navbar/\">Default</a></li>\r\n");
      out.write("            <li><a href=\"../navbar-static-top/\">Static top</a></li>\r\n");
      out.write("            ");
 if(session.getAttribute("mno") != null){
      out.write("\r\n");
      out.write("            <li><a href=\"logout\">LogOut <span class=\"sr-only\">(current)</span></a></li>\r\n");
      out.write("            ");
}else{
            	response.sendRedirect("index.jsp");
            }
            
      out.write("\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div><!--/.nav-collapse -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- Bootstrap core JavaScript\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("<!--     Placed at the end of the document so the pages load faster\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script> -->\r\n");
      out.write("    <script>window.jQuery || document.write('<script src=\"../../assets/js/vendor/jquery.min.js\"><\\/script>')</script>\r\n");
      out.write("    <!-- <script src=\"http://getbootstrap.com/dist/js/bootstrap.min.js\"></script> -->\r\n");
      out.write("    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\r\n");
      out.write("    <script src=http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@import url(//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css);\r\n");
      out.write("}\r\n");
      out.write("@import url(http://fonts.googleapis.com/css?family=Titillium+Web:300);\r\n");
      out.write(".fa-2x {\r\n");
      out.write("font-size: 2em;\r\n");
      out.write("}\r\n");
      out.write(".fa {\r\n");
      out.write("position: relative;\r\n");
      out.write("display: table-cell;\r\n");
      out.write("width: 60px;\r\n");
      out.write("height: 32px;\r\n");
      out.write("text-align: center;\r\n");
      out.write("vertical-align: middle;\r\n");
      out.write("font-size:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".main-menu:hover,nav.main-menu.expanded {\r\n");
      out.write("width:250px;\r\n");
      out.write("overflow:visible;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-menu {\r\n");
      out.write("background:#fbfbfb;\r\n");
      out.write("border-right:1px solid #e5e5e5;\r\n");
      out.write("position:absolute;\r\n");
      out.write("top:0;\r\n");
      out.write("bottom:0;\r\n");
      out.write("height:92%;\r\n");
      out.write("left:0;\r\n");
      out.write("width:60px;\r\n");
      out.write("overflow:hidden;\r\n");
      out.write("-webkit-transition:width .05s linear;\r\n");
      out.write("transition:width .05s linear;\r\n");
      out.write("-webkit-transform:translateZ(0) scale(1,1);\r\n");
      out.write("z-index:1000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-menu>ul {\r\n");
      out.write("margin:7px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-menu li {\r\n");
      out.write("position:relative;\r\n");
      out.write("display:block;\r\n");
      out.write("width:250px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-menu li>a {\r\n");
      out.write("position:relative;\r\n");
      out.write("display:table;\r\n");
      out.write("border-collapse:collapse;\r\n");
      out.write("border-spacing:0;\r\n");
      out.write("color:#999;\r\n");
      out.write(" font-family: arial;\r\n");
      out.write("font-size: 14px;\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("-webkit-transform:translateZ(0) scale(1,1);\r\n");
      out.write("-webkit-transition:all .1s linear;\r\n");
      out.write("transition:all .1s linear;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-menu .nav-icon {\r\n");
      out.write("position:relative;\r\n");
      out.write("display:table-cell;\r\n");
      out.write("width:60px;\r\n");
      out.write("height:34px;\r\n");
      out.write("text-align:center;\r\n");
      out.write("vertical-align:middle;\r\n");
      out.write("font-size:18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-menu .nav-text {\r\n");
      out.write("position:relative;\r\n");
      out.write("display:table-cell;\r\n");
      out.write("vertical-align:middle;\r\n");
      out.write("width:190px;\r\n");
      out.write("  font-family: 'Titillium Web', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-menu>ul.logout {\r\n");
      out.write("position:absolute;\r\n");
      out.write("left:0;\r\n");
      out.write("bottom:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".no-touch .scrollable.hover {\r\n");
      out.write("overflow-y:hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".no-touch .scrollable.hover:hover {\r\n");
      out.write("overflow-y:auto;\r\n");
      out.write("overflow:visible;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover,a:focus {\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav {\r\n");
      out.write("-webkit-user-select:none;\r\n");
      out.write("-moz-user-select:none;\r\n");
      out.write("-ms-user-select:none;\r\n");
      out.write("-o-user-select:none;\r\n");
      out.write("user-select:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul,nav li {\r\n");
      out.write("outline:0;\r\n");
      out.write("margin:0;\r\n");
      out.write("padding:0;\r\n");
      out.write("}\r\n");
      out.write(".main-menu li:hover>a,nav.main-menu li.active>a,.dropdown-menu>li>a:hover,.dropdown-menu>li>a:focus,.dropdown-menu>.active>a,.dropdown-menu>.active>a:hover,.dropdown-menu>.active>a:focus,.no-touch .dashboard-page nav.dashboard-menu ul li:hover a,.dashboard-page nav.dashboard-menu ul li.active a {\r\n");
      out.write("color:#fff;\r\n");
      out.write("background-color:#5fa2db;\r\n");
      out.write("}\r\n");
      out.write(".area {\r\n");
      out.write("float: left;\r\n");
      out.write("background: #e2e2e2;\r\n");
      out.write("width: 100%;\r\n");
      out.write("height: 100%;\r\n");
      out.write("}\r\n");
      out.write("@font-face {\r\n");
      out.write("  font-family: 'Titillium Web';\r\n");
      out.write("  font-style: normal;\r\n");
      out.write("  font-weight: 300;\r\n");
      out.write("  src: local('Titillium WebLight'), local('TitilliumWeb-Light'), url(http://themes.googleusercontent.com/static/fonts/titilliumweb/v2/anMUvcNT0H1YN4FII8wpr24bNCNEoFTpS2BTjF6FB5E.woff) format('woff');\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"col-md-3 visible-lg\" role=\"complementray\" style=\"padding-top: 0%\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<nav class=\"main-menu float_sidebar\">\r\n");
      out.write("\t\t            <ul class=\"bs-docs-sidenav\">\r\n");
      out.write("\t\t                <li>\r\n");
      out.write("\t\t                    <a href=\"#\">\r\n");
      out.write("\t\t                        <i class=\"fa fa-home fa-2x\"></i>\r\n");
      out.write("\t\t                        <span class=\"nav-text\">Dashboard</span>\r\n");
      out.write("\t\t                    </a>\r\n");
      out.write("\t\t                </li>\r\n");
      out.write("\t\t                <li class=\"has-subnav\">\r\n");
      out.write("\t\t                    <a href=\"#\">\r\n");
      out.write("\t\t                        <i class=\"fa fa-laptop fa-2x\"></i>\r\n");
      out.write("\t\t                        <span class=\"nav-text\">\r\n");
      out.write("\t\t                            UI Components\r\n");
      out.write("\t\t                        </span>\r\n");
      out.write("\t\t                    </a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t                </li>\r\n");
      out.write("\t\t                <li class=\"has-subnav\">\r\n");
      out.write("\t\t                    <a href=\"#\">\r\n");
      out.write("\t\t                       <i class=\"fa fa-list fa-2x\"></i>\r\n");
      out.write("\t\t                        <span class=\"nav-text\">\r\n");
      out.write("\t\t                            Forms\r\n");
      out.write("\t\t                        </span>\r\n");
      out.write("\t\t                    </a>\r\n");
      out.write("\t\t                </li>\r\n");
      out.write("\t\t                <li class=\"has-subnav\">\r\n");
      out.write("\t\t                    <a href=\"#\">\r\n");
      out.write("\t\t                       <i class=\"fa fa-folder-open fa-2x\"></i>\r\n");
      out.write("\t\t                        <span class=\"nav-text\">\r\n");
      out.write("\t\t                            Pages\r\n");
      out.write("\t\t                        </span>\r\n");
      out.write("\t\t                    </a>\r\n");
      out.write("\t\t                </li>\r\n");
      out.write("\t\t                <li>\r\n");
      out.write("\t\t                    <a href=\"#\">\r\n");
      out.write("\t\t                        <i class=\"fa fa-bar-chart-o fa-2x\"></i>\r\n");
      out.write("\t\t                        <span class=\"nav-text\">\r\n");
      out.write("\t\t                            Graphs and Statistics\r\n");
      out.write("\t\t                        </span>\r\n");
      out.write("\t\t                    </a>\r\n");
      out.write("\t\t                </li>\r\n");
      out.write("\t\t                <li>\r\n");
      out.write("\t\t                    <a href=\"#\">\r\n");
      out.write("\t\t                        <i class=\"fa fa-font fa-2x\"></i>\r\n");
      out.write("\t\t                        <span class=\"nav-text\">\r\n");
      out.write("\t\t                            Typography and Icons\r\n");
      out.write("\t\t                        </span>\r\n");
      out.write("\t\t                    </a>\r\n");
      out.write("\t\t                </li>\r\n");
      out.write("\t\t                <li>\r\n");
      out.write("\t\t                   <a href=\"#\">\r\n");
      out.write("\t\t                       <i class=\"fa fa-table fa-2x\"></i>\r\n");
      out.write("\t\t                        <span class=\"nav-text\">\r\n");
      out.write("\t\t                            Tables\r\n");
      out.write("\t\t                        </span>\r\n");
      out.write("\t\t                    </a>\r\n");
      out.write("\t\t                </li>\r\n");
      out.write("\t\t                <li>\r\n");
      out.write("\t\t                   <a href=\"#\">\r\n");
      out.write("\t\t                        <i class=\"fa fa-map-marker fa-2x\"></i>\r\n");
      out.write("\t\t                        <span class=\"nav-text\">\r\n");
      out.write("\t\t                            Maps\r\n");
      out.write("\t\t                        </span>\r\n");
      out.write("\t\t                    </a>\r\n");
      out.write("\t\t                </li>\r\n");
      out.write("\t\t                <li>\r\n");
      out.write("\t\t                    <a href=\"#\">\r\n");
      out.write("\t\t                       <i class=\"fa fa-info fa-2x\"></i>\r\n");
      out.write("\t\t                        <span class=\"nav-text\">\r\n");
      out.write("\t\t                            Documentation\r\n");
      out.write("\t\t                        </span>\r\n");
      out.write("\t\t                    </a>\r\n");
      out.write("\t\t                </li>\r\n");
      out.write("\t\t            </ul>\r\n");
      out.write("\r\n");
      out.write("\t\t            <ul class=\"logout\">\r\n");
      out.write("\t\t                <li>\r\n");
      out.write("\t\t                   <a href=\"logout\">\r\n");
      out.write("\t\t                         <i class=\"fa fa-power-off fa-2x\"></i>\r\n");
      out.write("\t\t                        <span class=\"nav-text\">\r\n");
      out.write("\t\t                            Logout\r\n");
      out.write("\t\t                        </span>\r\n");
      out.write("\t\t                    </a>\r\n");
      out.write("\t\t                </li>  \r\n");
      out.write("\t\t            </ul>\r\n");
      out.write("\t\t            \r\n");
      out.write("        \t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("    var $win = $(window);\r\n");
      out.write("    var top = $(window).scrollTop(); // 현재 스크롤바의 위치값을 반환합니다.\r\n");
      out.write(" \r\n");
      out.write("    /*사용자 설정 값 시작*/\r\n");
      out.write("    var speed          = 500;     // 따라다닐 속도 : \"slow\", \"normal\", or \"fast\" or numeric(단위:msec)\r\n");
      out.write("    var easing         = 'linear'; // 따라다니는 방법 기본 두가지 linear, swing\r\n");
      out.write("    var $layer         = $('.float_sidebar'); // 레이어 셀렉팅\r\n");
      out.write("    var layerTopOffset = 0;   // 레이어 높이 상한선, 단위:px\r\n");
      out.write("    $layer.css('position', 'relative').css('z-index', '1');\r\n");
      out.write("    /*사용자 설정 값 끝*/\r\n");
      out.write(" \r\n");
      out.write("    // 스크롤 바를 내린 상태에서 리프레시 했을 경우를 위해\r\n");
      out.write("    if (top > 0 )\r\n");
      out.write("        $win.scrollTop(layerTopOffset+top);\r\n");
      out.write("    else\r\n");
      out.write("        $win.scrollTop(0);\r\n");
      out.write(" \r\n");
      out.write("    //스크롤이벤트가 발생하면\r\n");
      out.write("    $(window).scroll(function(){\r\n");
      out.write("        yPosition = $win.scrollTop() - 0; //이부분을 조정해서 화면에 보이도록 맞추세요\r\n");
      out.write("        if (yPosition < 0)\r\n");
      out.write("        {\r\n");
      out.write("            yPosition = 0;\r\n");
      out.write("        }\r\n");
      out.write("        $layer.animate({\"top\":yPosition }, {duration:speed, easing:easing, queue:false});\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-color: white\">\r\n");
      out.write("\t<div style=\"padding-top: 2%\">\t<!--Top menubar와의 거리 2% -->\r\n");
      out.write("   <div class=\"container col-md-5 col-md-offset-0 \" style=\"background-color: rgb(250, 250, 250); padding-top: 1%; padding-bottom:2%\">\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /main.jsp(97,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("list");
      // /main.jsp(97,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/main.jsp(97,4) '${list }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("   \t\r\n");
            out.write("      <div class=\"row\">\r\n");
            out.write("         <div class=\"col-md-12\">\r\n");
            out.write("            <div class=\"thumbnail\" >\r\n");
            out.write("               <img alt=\"food\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.b_image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" height=\"400px\">\r\n");
            out.write("               <div class=\"caption\">\r\n");
            out.write("               <div class=\"row\">\r\n");
            out.write("                  <div class=\"col-md-12\">\r\n");
            out.write("                  <h3>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.b_mname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </h3>\r\n");
            out.write("                  <p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.b_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("                  </div>\r\n");
            out.write("               </div>\r\n");
            out.write("               <div class=\"row\">\r\n");
            out.write("                  <div class=\"col-md-12\">\r\n");
            out.write("                     &nbsp;<span class=\"glyphicon glyphicon-heart\" aria-hidden=\"true\"></span>&nbsp;\r\n");
            out.write("                     \t");
            out.write("\r\n");
            out.write("            \t\t\t ");
            if (_jspx_meth_c_005fset_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return;
            out.write("\r\n");
            out.write("                  ");
List<LikeDto> like = (List<LikeDto>)request.getAttribute((String)pageContext.getAttribute("like")); 
            out.write("\r\n");
            out.write("                  ");
if(like.size() == 0){ 
            out.write("\r\n");
            out.write("                  \t처음 좋아요의 주인공이 되세요\r\n");
            out.write("                  ");
}else if(like.size() >11){
                	  
            out.write("\r\n");
            out.write("                       ");
            out.print(like.size() );
            out.write("명이 좋아합니다\r\n");
            out.write("                       \r\n");
            out.write("                     ");
}
                  else if(like.size()<=11){
                	  for(LikeDto dto:like){
            out.write("\r\n");
            out.write("                      ");
            out.print(dto.getL_mname() );
            out.write(",\r\n");
            out.write("                    ");
}
            out.write("님이 좋아합니다");
}
                  
                  	
            out.write("\r\n");
            out.write("                     \r\n");
            out.write("            \t     \r\n");
            out.write("                  </div>\r\n");
            out.write("               </div>\r\n");
            out.write("               <div class=\"row\">\r\n");
            out.write("                  <div class=\"col-md-12\">\r\n");
            out.write("                  <div id=\"showreply");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.b_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                  ");
            if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return;
            out.write("\r\n");
            out.write("                  ");
List<ReplyDto> reply = (List<ReplyDto>)request.getAttribute((String)pageContext.getAttribute("re")); 
            out.write("\r\n");
            out.write("                     <table class=\"table-condensed small\" style=\"background-color: rgb(245, 245, 245); width: 100%\">\r\n");
            out.write("                    ");
for(ReplyDto dto:reply){
            out.write("\r\n");
            out.write("                       <tr>\r\n");
            out.write("                           <td><a href=\"#\">");
            out.print(dto.getR_name() );
            out.write("</a> ");
            out.print(dto.getR_content() );
            out.write("</td>\r\n");
            out.write("                        </tr>\r\n");
            out.write("                       \r\n");
            out.write("                     ");
} 
            out.write("\r\n");
            out.write("                     </table>\r\n");
            out.write("                     </div>\r\n");
            out.write("                  </div>\r\n");
            out.write("               </div>\r\n");
            out.write("               <div class=\"row top_pd\">\r\n");
            out.write("               <form action = \"insertReply\" method=\"post\" id = \"reply");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.b_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" name = \"reply\">\r\n");
            out.write("                  <div class=\"col-md-9\">\r\n");
            out.write("                  <div class=\"input-group\">\r\n");
            out.write("                     <span class=\"input-group-addon \" id=\"sizing-addon2\"><span class=\"glyphicon glyphicon-heart\"></span></span> \r\n");
            out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"답글달기...\" aria-describedby=\"sizing-addon2\" name=\"r_content\" id = \"r_content");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.b_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                        <input type=\"hidden\" name=\"r_bno\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list. b_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                        <input type=\"hidden\" name=\"r_mno\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                  </div>\r\n");
            out.write("                  </div>\r\n");
            out.write("                  <div class=\"col-md-3\">\r\n");
            out.write("                  <a href=\"javascript:;\" name = \"replySubmit");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.b_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn btn-default col-md-12\" role=\"button\">답글</a>\r\n");
            out.write("                  </div>\r\n");
            out.write("                  </form>\r\n");
            out.write("               </div>\r\n");
            out.write("               </div>\r\n");
            out.write("            </div>\r\n");
            out.write("         </div>\r\n");
            out.write("      </div>\r\n");
            out.write("      ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      }
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("    <div class=\"container col-md-3 col-md-offset-1\" >\r\n");
      out.write("      <div class=\"col-md-3 \" role=\"complementray\">\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-10 col-md-offset-2\">\r\n");
      out.write("               <nav class=\"bs-docs-sidebar hidden-print hidden-xs affix\">\r\n");
      out.write("                  <ul class=\"nav bs-docs-sidenav text-right\">\r\n");
      out.write("                     <li>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("현재 이벤트현재 이벤트현재 이벤트현재 이벤트</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-fixed-bottom\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("  \t<div class=\"row text-center\">\r\n");
      out.write("  \t \t하단 고정 바\r\n");
      out.write("  \t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /main.jsp(16,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("list");
    // /main.jsp(16,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/main.jsp(16,2) '${list }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t/* \t$.ajax({\r\n");
          out.write("\t\t\ttype:\"post\",\r\n");
          out.write("\t\t\turl:\"snslist\",\r\n");
          out.write("\t\t\tdata:{\"b_no\":\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.b_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"},\r\n");
          out.write("\t\t\tsuccess:function(data){\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\tvar like = data.likedata[0];\r\n");
          out.write("\t\t\t\tvar reply = data.replydata[0];\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\tvar str = \"<table class='table-condensed small' style='background-color: rgb(245, 245, 245); width: 100%'>\"\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\tjQuery(reply).each(function(index, objArr){\r\n");
          out.write("\t\t\t\t\tstr += \"<tr>\";\r\n");
          out.write("\t\t\t\t\tstr += \"<td><a href='#'>\" + objArr.r_name +\"</a>\"+ objArr.r_content + \"</td>\";\r\n");
          out.write("\t\t\t\t\tstr += \"</tr>\";\r\n");
          out.write("\t\t\t\t})\r\n");
          out.write("\t\t\t\tstr += \"</table>\";\r\n");
          out.write("\t\t\t\tjQuery(\"#showreply");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.b_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\").html(str);\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t},error:function(request,status,error){\r\n");
          out.write("\t\t        alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
          out.write("\t\t       }\r\n");
          out.write("\t\t}); */\r\n");
          out.write("\t\tjQuery('a[name=replySubmit");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.b_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("]').click(function(){\r\n");
          out.write("\t\t\t//$(\"#reply\").submit();\r\n");
          out.write("\t\t\tjQuery(\"#showreply");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.b_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\").empty();\r\n");
          out.write("\t\t\t  \r\n");
          out.write("\t\t$.ajax({\r\n");
          out.write("\t\t\ttype:\"post\",\r\n");
          out.write("\t\t\turl:\"insertReply\",\r\n");
          out.write("\t\t\tdata:$(\"#reply");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.b_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\").serialize(),\r\n");
          out.write("\t\t\tsuccess:function(replyData){\r\n");
          out.write("\t\t\t\tvar str = \"<table class='table-condensed small' style='background-color: rgb(245, 245, 245); width: 100%'>\"\r\n");
          out.write("\t\t\t\tvar list = replyData.datas;\r\n");
          out.write("\t\t\t\tjQuery(list).each(function(index, objArr){\r\n");
          out.write("\t\t\t\t\tstr += \"<tr>\";\r\n");
          out.write("\t\t\t\t\tstr += \"<td><a href='#'>\" + objArr.r_name +\"</a>\"+ objArr.r_content + \"</td>\";\r\n");
          out.write("\t\t\t\t\tstr += \"</tr>\";\r\n");
          out.write("\t\t\t\t})\r\n");
          out.write("\t\t\t\tstr += \"</table>\";\r\n");
          out.write("\t\t\t\tjQuery(\"#showreply");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.b_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\").html(str);\r\n");
          out.write("\t\t\t\tjQuery(\"#r_content");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.b_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\").val(\"\");\r\n");
          out.write("\t\t\t}\r\n");
          out.write("\t\t});\r\n");
          out.write("\t\t});\r\n");
          out.write("\t\t\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
    // /main.jsp(119,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("like");
    // /main.jsp(119,16) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/main.jsp(119,16) 'like${list.b_no}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"like${list.b_no}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
    // /main.jsp(141,18) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("re");
    // /main.jsp(141,18) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/main.jsp(141,18) 'reply${list.b_no}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"reply${list.b_no}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }
}
